<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search agreement
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["agreement/new", "Create agreement"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "agreement/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<p>Prueba</p>
<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldObjective" class="col-sm-2 control-label">Objective</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["objective", "size" => 30, "class" => "form-control", "id" => "fieldObjective"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValidTo" class="col-sm-2 control-label">Valid Of To</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["valid_to", "size" => 30, "class" => "form-control", "id" => "fieldValidTo"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdEntityFrom" class="col-sm-2 control-label">Id Of Entity Of From</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_entity_from", "type" => "number", "class" => "form-control", "id" => "fieldIdEntityFrom"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdEntityWith" class="col-sm-2 control-label">Id Of Entity Of With</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_entity_with", "type" => "number", "class" => "form-control", "id" => "fieldIdEntityWith"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
