<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="card">
        <div class="header">
            <nav>
            <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["agreement/search", "Regresar"]) ?></li>
            </ul>
            </nav>
          <h4 class="title">Nuevo registro de Convenios</h4>
          <hr>
         
        </div>
        
        <div class="content ">

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "agreement/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Nombre del convenio</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldObjective" class="col-sm-2 control-label">Objetivo</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["objective", "size" => 30, "class" => "form-control", "id" => "fieldObjective" , "style"=>"resize:none"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldValidTo" class="col-sm-2 control-label">Válido hasta</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(["valid_to", "size" => 30, "class" => "form-control", "id" => "fieldValidTo"]) ?>
    </div>
</div>
   

 <div class="form-group">
        <label for="fieldIdEntityWith" class="col-sm-2 control-label">¿Con qué entidad?</label>
        <div class="col-sm-10">
            <?php 
		    echo $this->tag->select(array("id_entity_with",
		                                    		Entity::find(),
		                                    		"class"=> "form-control",
		                                    		"id"=>"fieldIdEntityWith",
		                                    		"useEmpty"  =>  true,
		                                    		"emptyText" =>  "Seleccione una entidad",
		                                    		"using" => array("id", "name"),));
    
             ?>
        </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

        <?php echo $this->tag->endForm(); ?>
        </div>
      </div>
    </div>
  </div>
</div>

