<?php
  /**
   * @var \Phalcon\Mvc\View\Engine\Php $this
   */
  ?>
<?php use Phalcon\Tag; ?>

<style>
 table {
  table-layout: fixed;
  width: 100%;
  }
  td {
  }
  table th{
    font-weight: bold;
  }

</style>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
    <?php echo $this->getContent(); ?>
    </div>
    <div class="col-md-12 col-sm-12">
    
      <div class="card">
        <div class="header">
          <h4 class="title">Convenios</h4>
          <hr>
          <?php
          echo $this->tag->linkTo(array('agreement/new', "<i class='fas fa-plus-circle' style='color:green'>Crear nueva</i>"));
          ?>       
         
        </div>
        
        <div class="content ">
          
          <table class="table table-hover">
            <thead>
              <tr class="info">
                <th  class="text-center">#</th>
                <th  class="text-center">Nombre</th>
                <th  class="text-center">¿Con quién?</th>
                <th  class="text-center">Objetivo</th>
                <th  class="text-center">Vigencia</th>
                <th  class="text-center"></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($page->items as $agreement): ?>
              <tr>
                <td class="text-center"><?php echo $agreement->id ?></td>
                <td class="text-center"><?php echo $agreement->name ?></td>
                <td class="text-center"><?php echo Entity::findFirst($agreement->id_entity_with)->name ?></td>
                <td class="text-center"><?php echo $agreement->objective ?></td>
                <td class="text-center"><?php echo date("Y-m-d", strtotime($agreement->valid_to)) ?></td>
               
                <td class="text-center">
                  <?php echo $this->tag->linkTo(["agreement/edit/" . $agreement->id, "Editar"]); ?>
                </td>
              </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
          <div class="row">
            <div class="col-sm-1">
              <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                <?php echo $page->current, "/", $page->total_pages ?>
              </p>
            </div>
            <div class="col-sm-11">
              <nav>
                <ul class="pagination">
                  <li>
                    <?php echo $this->tag->linkTo("agreement/search", "Primero") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("agreement/search?page=" . $page->before, "Anterior") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("agreement/search?page=" . $page->next, "Siguiente") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("agreement/search?page=" . $page->last, "Último") ?>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
