<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
   
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="card">
        <div class="header">
            <nav>
            <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["visitor", "Regresar"]) ?></li>
            </ul>
            </nav>
          <h4 class="title">Crear Visitante</h4>
          <hr>
         
        </div>
        
        <div class="content ">


        <?php
            echo $this->tag->form(
                [
                    "visitor/create",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>

        <div class="form-group">
            <label for="fieldIdVisitor" class="col-sm-2 control-label">Nombre visitante</label>
            <div class="col-sm-10">
                <?php 
                echo $this->tag->select(array("id_visitor_person",
                                                        Person::find('id_role = 3'),
                                                        "class"=> "form-control",
                                                        "id"=>"fieldIdVisitor",
                                                        "useEmpty"  =>  true,
                                                        "emptyText" =>  "Seleccione un visitante",
                                                        "using" => array("id", "name"),));
        
                ?>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldObjective" class="col-sm-2 control-label">Objetivo</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["objective", "type" => "text", "class" => "form-control", "id" => "fieldObjective"]) ?>
            </div>
        </div>

        <div class="form-group">
            <label for="fieldArrivalDate" class="col-sm-2 control-label">Fecha de llegada</label>
            <div class="col-sm-10">
                <?php echo $this->tag->dateField(["arrival_date", "size" => 30, "class" => "form-control", "id" => "fieldArrivalDate"]) ?>
            </div>
         </div>

         <div class="form-group">
            <label for="fieldDepartureDate" class="col-sm-2 control-label">Fecha de regreso</label>
            <div class="col-sm-10">
                <?php echo $this->tag->dateField(["departure_date", "size" => 30, "class" => "form-control", "id" => "fieldDepartureDate"]) ?>
            </div>
         </div>
        
    
        


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-default"]) ?>
            </div>
        </div>

        <?php echo $this->tag->endForm(); ?>
        </div>
      </div>
    </div>
  </div>
</div>