<?php
  /**
   * @var \Phalcon\Mvc\View\Engine\Php $this
   */
  ?>
<?php use Phalcon\Tag; ?>

<style>
 table {
  table-layout: fixed;
  width: 100%;
  }
  td {
  }

</style>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
    <?php echo $this->getContent(); ?>
    </div>
    <div class="col-md-12 col-sm-12">
    
      <div class="card">
        <div class="header">
          <h4 class="title">Visitantes</h4>
          <hr>
          <?php
          echo $this->tag->linkTo(array('visitor/new', "<i class='fas fa-plus-circle' style='color:green'>Crear nueva</i>"));
          ?>       
         
        </div>
        
        <div class="content  ">
          
        <table class="table table-hover">
            <thead>
              <tr class="info">
                <th  class="text-center">#</th>
                <th  class="text-center">Nombre </th>
                <th  class="text-center">Entidad de origen</th>
                <th  class="text-center">País</th>
                <th  class="text-center">Objeto</th>
                <th  class="text-center">Año</th>
                <th  class="text-center">Duración de la estadia</th>
                <th  class="text-center"></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($page->items as $visitor): ?>
              <tr>
                <td class="text-center"><?php echo $visitor->id ?></td>
                <td class="text-center"><?php echo $visitor->Person->name ?></td>
                <td class="text-center"><?php echo $visitor->Person->Program->Entity->name ?></td>          
                <td class="text-center"><?php echo $visitor->Person->Program->Entity->Country->name ?></td>              
                <td class="text-center"><?php echo $visitor->objective?></td>
                <td class="text-center"><?php echo date("Y", strtotime($visitor->arrival_date))?></td>
                <td class="text-center"><?php echo date("Y-m-d", strtotime($visitor->arrival_date)). " hasta ".date("Y-m-d", strtotime($visitor->departure_date))?></td>                
                <td class="text-center">
                  <?php echo $this->tag->linkTo(["visitor/edit/" . $visitor->id, "Editar"]); ?>
                </td>
              </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
          <div class="row">
            <div class="col-sm-1">
              <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                <?php echo $page->current, "/", $page->total_pages ?>
              </p>
            </div>
            <div class="col-sm-11">
              <nav>
                <ul class="pagination">
                  <li>
                    <?php echo $this->tag->linkTo("innovation/search", "Primero") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("innovation/search?page=" . $page->before, "Anterior") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("innovation/search?page=" . $page->next, "Siguiente") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("innovation/search?page=" . $page->last, "Último") ?>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
