<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
   
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="card">
        <div class="header">
            <nav>
            <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["extension", "Regresar"]) ?></li>
            </ul>
            </nav>
          <h4 class="title">Crear Extensión/Actividad</h4>
          <hr>
         
        </div>
        
        <div class="content ">


        <?php
            echo $this->tag->form(
                [
                    "extension/create",
                    "autocomplete" => "off",
                    "class" => "form-horizontal"
                ]
            );
        ?>

        <div class="form-group">
            <label for="fieldName" class="col-sm-2 control-label">Nombre</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
            </div>
        </div>

        <div class="form-group">
        <label for="fieldIdCoordinator" class="col-sm-2 control-label">Coordinador</label>
        <div class="col-sm-10">
            <?php 
		    echo $this->tag->select(array("id_coordinator",
		                                    		Person::find('id_role = 1'),
		                                    		"class"=> "form-control",
		                                    		"id"=>"fieldIdCoordinator",
		                                    		"useEmpty"  =>  true,
		                                    		"emptyText" =>  "Seleccione un coordinador",
		                                    		"using" => array("id", "name"),));
    
             ?>
        </div>
        </div>

         <div class="form-group">
        <label for="fieldIdType" class="col-sm-2 control-label">Tipo</label>
        <div class="col-sm-10">
            <?php 
		    echo $this->tag->select(array("id_type",
		                                    		ExtensionType::find(),
		                                    		"class"=> "form-control",
		                                    		"id"=>"fieldIdType",
		                                    		"useEmpty"  =>  true,
		                                    		"emptyText" =>  "Seleccione un tipo de extensión",
		                                    		"using" => array("id", "name"),));
    
             ?>
        </div>
    </div>

     <div class="form-group">
        <label for="fieldIdProgram" class="col-sm-2 control-label">Programa</label>
        <div class="col-sm-10">
            <?php 
		    echo $this->tag->select(array("id_program",
		                                    		Program::find(),
		                                    		"class"=> "form-control",
		                                    		"id"=>"fieldIdProgram",
		                                    		"useEmpty"  =>  true,
		                                    		"emptyText" =>  "Seleccione un programa",
		                                    		"using" => array("id", "name"),));
    
             ?>
        </div>
    </div>

        <div class="form-group">
            <label for="fieldUsers" class="col-sm-2 control-label">Dirigodo a</label>
            <div class="col-sm-10">
                <?php echo $this->tag->textField(["users", "type" => "text", "class" => "form-control", "id" => "fieldUsers"]) ?>
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-default"]) ?>
            </div>
        </div>

        <?php echo $this->tag->endForm(); ?>
        </div>
      </div>
    </div>
  </div>
</div>