<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12 col-sm-12">
      <div class="card">
        <div class="header">
            <nav>
            <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["person/search", "Regresar"]) ?></li>
            </ul>
            </nav>
          <h4 class="title">Nuevo registro de Persona</h4>
          <hr>
         
        </div>
        
        <div class="content ">

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "person/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Nombre</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

 <div class="form-group">
        <label for="fieldPersonRole" class="col-sm-2 control-label">Rol</label>
        <div class="col-sm-10">
            <?php 
		    echo $this->tag->select(array("id_role",
		                                    		PersonRole::find(),
		                                    		"class"=> "form-control",
		                                    		"id"=>"fieldPersonRole",
		                                    		"useEmpty"  =>  true,
		                                    		"emptyText" =>  "Seleccione un rol",
		                                    		"using" => array("id", "name"),));
    
             ?>
        </div>
</div>

 <div class="form-group">
        <label for="fieldIdProgram" class="col-sm-2 control-label">Programa</label>
        <div class="col-sm-10">
            <?php 
		    echo $this->tag->select(array("id_program",
		                                    		Program::find(),
		                                    		"class"=> "form-control",
		                                    		"id"=>"fieldIdProgram",
		                                    		"useEmpty"  =>  true,
		                                    		"emptyText" =>  "Seleccione un programa",
		                                    		"using" => array("id", "name"),));
    
             ?>
        </div>
</div>



<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Guardar", "class" => "btn btn-success"]) ?>
    </div>
</div>

        <?php echo $this->tag->endForm(); ?>
        </div>
      </div>
    </div>
  </div>
</div>

