<?php
  /**
   * @var \Phalcon\Mvc\View\Engine\Php $this
   */
  ?>
<?php use Phalcon\Tag; ?>

<style>
 table {
  table-layout: fixed;
  width: 100%;
  }
  td {
  }

</style>


<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
    <?php echo $this->getContent(); ?>
    </div>
    <div class="col-md-12 col-sm-12">
    
      <div class="card">
        <div class="header">
          <h4 class="title">Personas</h4>
          <hr>
          <?php
          echo $this->tag->linkTo(array('person/new', "<i class='fas fa-plus-circle' style='color:green'>Crear nueva</i>"));
          ?>       
         
        </div>
        
        <div class="content  ">
          
        <table class="table table-hover">
            <thead>
              <tr class="info">
                <th  class="text-center">ID</th>
                <th  class="text-center">Nombre</th>   
                <th  class="text-center">Rol</th> 
                <th  class="text-center">Programa</th>  
                <th  class="text-center">Universidad</th>             
                <th  class="text-center"></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($page->items as $person): ?>
              <tr>
                <td class="text-center"><?php echo $person->id ?></td>
                <td class="text-center"><?php echo $person->name ?></td>
                <td class="text-center"><?php echo $person->PersonRole->name ?></td>
                <td class="text-center"><?php echo $person->Program->name ?></td>
                <td class="text-center"><?php echo $person->Program->Entity->name ?></td>
              
                <td class="text-center">
                  <?php echo $this->tag->linkTo(["person/edit/" . $person->id, "Editar"]); ?>
                </td>
              </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
          <div class="row">
            <div class="col-sm-1">
              <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
                <?php echo $page->current, "/", $page->total_pages ?>
              </p>
            </div>
            <div class="col-sm-11">
              <nav>
                <ul class="pagination">
                  <li>
                    <?php echo $this->tag->linkTo("person/search", "Primero") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("person/search?page=" . $page->before, "Anterior") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("person/search?page=" . $page->next, "Siguiente") ?>
                  </li>
                  <li>
                    <?php echo $this->tag->linkTo("person/search?page=" . $page->last, "Último") ?>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
