<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>POLI APP</title>
       <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        --> <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
     <!--     Fonts and icons     -->
    
    <?php $this->assets->outputCss('headercss'); ?>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="<?php echo $this->url->get('/css/pe-icon-7-stroke.css')?>" type='text/css' />
    <?php $this->assets->outputJs('headerjs'); ?>
    </head>
    <?php if($this->session->get('auth')) { ?>
    <body>
    <div class="wrapper">        
    <div class="sidebar" data-color="blue" data-image="<?php echo $this->url->get('/img/sidebar-51.png')?>">
    	<div class="sidebar-wrapper">
            <div class="logo">
                <a href="" class="simple-text">
                    Poli App
                </a>
            </div>

            <ul class="nav">

             <?php
                foreach($mainMenuOptions as $option){
                    echo '<li>';
                    echo $this->tag->linkTo(array($option->getAction(), "<i class='" . $option->getClass() . "'></i> <p>" . $option->getTitle() . "</p>"));
                    echo '</li>';
                }
                ?>
				
            </ul>
    	</div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"></a>
                </div>
                <div class="collapse navbar-collapse">
                  
                <ul class="nav navbar-nav navbar-left">
                <li>
                <?php
        
                echo $this->tag->linkTo(array("api/ExportData", 'Descargar datos' , 'class' => 'pe-7s-download')); ?>
                   
                <li>
                </ul>
                    <ul class="nav navbar-nav navbar-right">                   
                        <li>
                        <?php
        
                        echo $this->tag->linkTo(array("session/logout", 'Cerrar sesión')); ?>
                        </li>
						<li class="separator hidden-lg"></li>
                    </ul>
                </div>
            </div>
        </nav>


        <div class="content">
            <?php echo $this->getContent(); ?>
        </div>


        <footer class="footer">
            <div class="container-fluid">
               
                <p class="copyright pull-right">
                    &copy; PoliApp 2018
                </p>
            </div>
        </footer>

    </div>
</div>

    <?php } else { ?>

        <style>
            html,
            body {
            height: 100%;
            }

            body {
                
                margin-bottom: 60px; 
                background-color: #ffffff;
            }

            .container{
                margin-top: 40px;
                padding-left: 40px;
                padding-right: 40px;
                max-width: 540px;
                
            }

            textarea{
                resize: none;
            }
  

        </style>
     
        <body class="text-center">
        <div class="content">
            <?php echo $this->getContent(); ?>
        </div>


        <footer class="footer">
            <div class="container-fluid">
               
                <p class="copyright pull-right">
                    &copy; PoliApp 2018
                </p>
            </div>
        </footer>

    <?php }?>
      
       <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

       <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        -->
       
    </body>
</html>
