<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["extension_project", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create extension_project
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "extension_project/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdFinancing" class="col-sm-2 control-label">Id Of Financing</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_financing", "type" => "number", "class" => "form-control", "id" => "fieldIdFinancing"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdExtension" class="col-sm-2 control-label">Id Of Extension</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id_extension", "type" => "number", "class" => "form-control", "id" => "fieldIdExtension"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
