<div class="row">
    <?php
    foreach($options as $option){
        echo '<div class="col-sm-6 col-md-4 col-lg-3">';
        echo  $this->tag->linkTo(array($option->getAction(), '
            <div class="card">
                <div class="header text-center">
                    <h6 class="title">' . $option->getTitle() . '</h4>
                </div>
                <div class="content text-center">
                    <i class="' . $option->getClass() . '" style="font-size: 50px;"></i>
                </div>
            </div>
        '));
        echo '</div>';
    }
    ?>
</div>